export const defaultEnrollmentFormConfig = {
  sections: [
    {
      id: "student",
      title: "Informacion del Alumno",
      description: "Datos personales del alumno que se inscribe.",
      fields: [
        {
          id: "student_name",
          type: "text",
          label: "Nombre completo",
          placeholder: "Ej: Maria Lopez",
          required: true,
          maxLength: 100,
        },
        {
          id: "student_email",
          type: "email",
          label: "Correo electronico",
          placeholder: "maria@ejemplo.com",
          required: true,
          maxLength: 255,
        },
        {
          id: "student_phone",
          type: "tel",
          label: "Telefono",
          placeholder: "(011) 1234-5678",
          required: true,
          maxLength: 20,
        },
        {
          id: "student_birthdate",
          type: "date",
          label: "Fecha de nacimiento",
          required: true,
        },
        {
          id: "student_level",
          type: "select",
          label: "Nivel de experiencia",
          required: true,
          options: [
            { value: "beginner", label: "Principiante" },
            { value: "intermediate", label: "Intermedio" },
            { value: "advanced", label: "Avanzado" },
          ],
        },
      ],
    },
    {
      id: "guardian",
      title: "Informacion del Tutor",
      description: "Requerido para alumnos menores de 18 anos.",
      fields: [
        {
          id: "guardian_name",
          type: "text",
          label: "Nombre del tutor",
          placeholder: "Nombre completo",
          required: false,
          maxLength: 100,
        },
        {
          id: "guardian_phone",
          type: "tel",
          label: "Telefono del tutor",
          placeholder: "(011) 1234-5678",
          required: false,
          maxLength: 20,
        },
        {
          id: "guardian_email",
          type: "email",
          label: "Correo del tutor",
          placeholder: "tutor@ejemplo.com",
          required: false,
          maxLength: 255,
        },
      ],
      conditions: [
        {
          id: "cond_guardian_age",
          sourceFieldId: "student_birthdate",
          operator: "date_after",
          value: "today_minus_18y",
        },
      ],
    },
    {
      id: "payer_info",
      title: "Datos del Pagador y Forma de Pago",
      description: "Permite usar datos del alumno, tutor o de otra persona.",
      fields: [
        {
          id: "payer_type",
          type: "select",
          label: "Quien realiza el pago?",
          required: true,
          options: [
            { value: "student", label: "El propio alumno" },
            { value: "guardian", label: "Tutor o responsable" },
            { value: "other", label: "Otra persona" },
          ],
        },
        {
          id: "payer_name",
          type: "text",
          label: "Nombre del pagador",
          placeholder: "Solo si paga otra persona",
          required: false,
          maxLength: 100,
          conditions: [
            { id: "cond_payer_name_other", sourceFieldId: "payer_type", operator: "equals", value: "other" },
          ],
        },
        {
          id: "payer_email",
          type: "email",
          label: "Email del pagador",
          placeholder: "correo@ejemplo.com",
          required: false,
          maxLength: 255,
          conditions: [
            { id: "cond_payer_email_other", sourceFieldId: "payer_type", operator: "equals", value: "other" },
          ],
        },
        {
          id: "payer_phone",
          type: "tel",
          label: "Telefono del pagador",
          placeholder: "(000) 0000-0000",
          required: false,
          maxLength: 20,
          conditions: [
            { id: "cond_payer_phone_other", sourceFieldId: "payer_type", operator: "equals", value: "other" },
          ],
        },
        {
          id: "payment_method",
          type: "select",
          label: "Método de pago",
          required: true,
          options: [
            { value: "transfer", label: "Transferencia bancaria" },
            { value: "cash", label: "Efectivo" },
            { value: "card", label: "Tarjeta de credito/debito" },
            { value: "mercadopago", label: "Mercado Pago" },
          ],
        },
      ],
    },
    {
      id: "additional",
      title: "Informacion Adicional",
      fields: [
        {
          id: "medical_notes",
          type: "textarea",
          label: "Condiciones medicas o alergias",
          placeholder: "Indica cualquier condicion relevante...",
          required: false,
          maxLength: 500,
        },
        {
          id: "how_found",
          type: "select",
          label: "Como nos conociste?",
          required: false,
          options: [
            { value: "social", label: "Redes sociales" },
            { value: "friend", label: "Recomendacion" },
            { value: "search", label: "Busqueda en internet" },
            { value: "other", label: "Otro" },
          ],
        },
        {
          id: "terms",
          type: "checkbox",
          label: "Consentimiento",
          placeholder: "He leido y acepto los terminos y condiciones de inscripcion",
          required: true,
        },
        {
          id: "selector_condition_info",
          type: "info",
          label: "Condicion de ejemplo",
          placeholder: "Este bloque aparece porque la fecha de nacimiento es anterior a hoy hace 18 anos (mayor de edad). Asi funcionan las condiciones de visibilidad: puedes mostrar u ocultar campos segun los valores introducidos anteriormente.",
          required: false,
          conditions: [
            { id: "cond_selector_info_age", sourceFieldId: "student_birthdate", operator: "date_before", value: "today_minus_18y" },
          ],
        },
      ],
    },
    {
      id: "documents",
      title: "Documentos",
      description: "Adjunta los documentos requeridos (opcional).",
      fields: [
        {
          id: "id_document",
          type: "file",
          label: "Documento de identidad (DNI)",
          required: false,
          accept: ".pdf,.jpg,.jpeg,.png",
        },
        {
          id: "medical_cert",
          type: "file",
          label: "Certificado medico",
          required: false,
          accept: ".pdf,.jpg,.jpeg,.png",
        },
      ],
    },
  ],
  jointEnrollment: {
    enabled: false,
    maxStudents: 3,
  },
  includeSchedule: true,
  includePricing: true,
  scheduleSettings: {
    preferredView: "calendar",
    recurringSelectionMode: "linked",
    recurringClassOverrides: [],
    calendarFields: {
      showDiscipline: true,
      showCategory: false,
      showRoom: true,
      showCapacity: true,
      showPrice: true,
      showSelectedStudents: true,
    },
  },
} as const;
